#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload=$(cat <&0) # STDIN params

id=$(get_id "$payload")
json=$(find_by_id "onboardsupport" pablodepacas@hotmail.com 124816 $id)
date=$(get_last_date "$json")
json=$(find_after_timestamp "onboardsupport" pablodepacas@hotmail.com 124816 $date)
ids=$(get_ids "$json")
to_return=$(transform "$ids")

echo $to_return >&3
